### ISSUE TITLE
Changing output directory doesn't work, still outputs in default location and also first screen still says version 0.2

### ISSUE THREAD

**Issue by Arslet** [sagishporer/bulk-actions-for-paint-dot-net#3]
[I chose a picture to convert, and chose where to output it](https://i.imgur.com/iGKzP8t.png)

However, [it still outputted it in Pictures\BulkActionForPaintDotNet\2018.4.13](https://i.imgur.com/5PyHgJU.png)  
  
Also, I spotted another small mistake, [in the first screen when you open the plugin it still says version 0.2](https://i.imgur.com/Tji0R4P.png)

**Comment by sagishporer** [comment]
Thank you for your feedback.

Both issues now fixed in v0.3.1
