### ISSUE TITLE
plugin crashes with new paint.net 4.1

### ISSUE THREAD

**Issue by tegetegede** [sagishporer/bulk-actions-for-paint-dot-net#6]
just to report that the plugin crashes with new paint.net 4.1 (standalone and W10 app),
attached is the crash log from the W10 app
[pdncrash.1.log](https://github.com/sagishporer/bulk-actions-for-paint-dot-net/files/2363051/pdncrash.1.log)

**Comment by sagishporer** [comment]
It seems a validation of the items in the "Edit" menu was added. The menu item must be moved to the "Effects" menu. Will do that as soon as possible.

**Comment by sagishporer** [comment]
Issue fixed in version 0.4: Moved the from the "Edit" menu to the "Effects" menu.
