### ISSUE TITLE
Bulk Actions doesn't appear in the effects menu

### ISSUE THREAD

**Issue by Arslet** [sagishporer/bulk-actions-for-paint-dot-net#7]
https://i.imgur.com/Ukojvdx.png

I'm using paint.net 4.1.3 and bulk actions 1.0. I've restarted the program a few times but it had no effect.

**Comment by sagishporer** [comment]
Issue reproduced. I'll try to fix it.

**Comment by sagishporer** [comment]
Issue fixed in plug-in version v1.1
